@startuml

skinparam classAttributeIconSize 0

package "Dto" {
  package "Reservation" {
		class CreateReservationDto {
			- courtId: UUID
			- startTime: LocalDateTime
			- endTime: LocalDateTime
			- gameType: GameType
			- customerPhoneNumber: String
			- customerName: String
		}

		class UpdateReservationDto {
			- courtId: UUID
			- startTime: LocalDateTime
			- endTime: LocalDateTime
			- gameType: GameType
		}

		class ReservationPreviewDto {
			- id: UUID
			- courtName: String
			- customerName: String
			- startTime: LocalDateTime
			- endTime: LocalDateTime
		}

		class ReservationDetailDto {
			- id: UUID
			- courtDetailDto: CourtDetailDto
			- customerDetailDto: CustomerDetailDto
			- startTime: LocalDateTime
			- endTime: LocalDateTime
			- gameType: GameType
			- price: Price
			- deleted: boolean
			- createdAt: LocalDateTime
		}

		class CourtReservationListDto {
			- court: CourtDetailDto
			- reservations: List<ReservationPreviewDto>
		}
	}

	package "Court" {
		class CreateCourtDto {
			- name: String
			- surfaceTypeId: UUID
		}

		class UpdateCourtDto {
			- name: String
			- surfaceTypeId: UUID
		}

		class CourtDetailDto {
			- id: UUID
			- name: String
			- surfaceTypeName: String
			- deleted: boolean
		}
	}

	package "SurfaceType" {
	  class CreateSurfaceTypeDto {
	    - name: String
	    - pricePerMinute: Price
	  }

	  class UpdateSurfaceTypeDto {
	    - name: String
	    - pricePerMinute: Price
	  }

	  class SurfaceTypeDetailDto {
	    - id: UUID
	    - name: String
	    - pricePerMinute: Price
	    - deleted: boolean
	  }
	}

	package "Customer" {
		class CreateCustomerDto {
			- phoneNumber: String
			- name: String
		}

		class UpdateCustomerDto {
			- phoneNumber: String
			- name: String
		}

		class CustomerDetailDto {
			- id: UUID
			- phoneNumber: String
			- name: String
			- deleted: boolean
		}
	}

	package "User" {
	  class CreateUserDto {
	    - email: String
	    - password: String
	    - role: UserRole
	  }

	  class UpdateUserDto {
	    - email: String
	    - role: UserRole
	  }

	  class UserDetailDto {
	    - id: UUID
	    - email: String
	    - role: UserRole
	    - deleted: boolean
	  }
	}

	class Price {
		- amount: BigDecimal
		- currency: String
	}

	enum GameType {
    SINGLES
    DOUBLES
  }

  enum UserRole {
    USER
    ADMIN
  }
}

@enduml