@startuml

skinparam classAttributeIconSize 0

package "SurfaceType" {

	package "model" {
	  class SurfaceType {
      - id: UUID
      - name: String
      - pricePerMinute: Price
      - deleted: boolean
    }
	}

	package "dto" {
	  class CreateSurfaceTypeDto {
	    - name: String
	    - pricePerMinute: Price
	  }

	  class UpdateSurfaceTypeDto {
	    - name: String
	    - pricePerMinute: Price
	  }

	  class SurfaceTypeDetailDto {
	    - id: UUID
	    - name: String
	    - pricePerMinute: Price
	    - deleted: boolean
	  }
	}

	package "service" {
		class SurfaceTypeService {
			+ createSurfaceType(dto: CreateSurfaceTypeDto): SurfaceTypeDetailDto
			+ updateSurfaceType(id: UUID, dto: UpdateSurfaceTypeDto): SurfaceTypeDetailDto
			+ getAllSurfaceTypes(): List<SurfaceTypeDetailDto>
			+ softDeleteSurfaceType(id: UUID): void
		}
	}

	package "controller" {
		class SurfaceTypeController {
			+ createSurfaceType(dto: CreateSurfaceTypeDto): SurfaceTypeDetailDto
			+ updateSurfaceType(id: UUID, dto: UpdateSurfaceTypeDto): SurfaceTypeDetailDto
			+ deleteSurfaceType(id: UUID): void
			+ getAllSurfaceTypes(): List<SurfaceTypeDetailDto>
		}
	}
}

@enduml